// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VManBackend.Infrastructure.Immich.Generated.Models;
namespace VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets
{
    /// <summary>
    /// Builds and executes requests for operations under \search\large-assets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LargeAssetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LargeAssetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/large-assets{?albumIds*,city*,country*,createdAfter*,createdBefore*,isEncoded*,isFavorite*,isMotion*,isNotInAlbum*,isOffline*,lensModel*,libraryId*,make*,minFileSize*,model*,ocr*,personIds*,rating*,size*,state*,tagIds*,takenAfter*,takenBefore*,trashedAfter*,trashedBefore*,type*,updatedAfter*,updatedBefore*,visibility*,withDeleted*,withExif*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LargeAssetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/large-assets{?albumIds*,city*,country*,createdAfter*,createdBefore*,isEncoded*,isFavorite*,isMotion*,isNotInAlbum*,isOffline*,lensModel*,libraryId*,make*,minFileSize*,model*,ocr*,personIds*,rating*,size*,state*,tagIds*,takenAfter*,takenBefore*,trashedAfter*,trashedBefore*,type*,updatedAfter*,updatedBefore*,visibility*,withDeleted*,withExif*}", rawUrl)
        {
        }
        /// <summary>
        /// Search for assets that are considered large based on specified criteria.
        /// </summary>
        /// <returns>A List&lt;global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>?> PostAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder.LargeAssetsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>> PostAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder.LargeAssetsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>(requestInfo, global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Search for assets that are considered large based on specified criteria.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder.LargeAssetsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder.LargeAssetsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search for assets that are considered large based on specified criteria.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LargeAssetsRequestBuilderPostQueryParameters 
        {
            /// <summary>Filter by album IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("albumIds")]
            public Guid?[]? AlbumIds { get; set; }
#nullable restore
#else
            [QueryParameter("albumIds")]
            public Guid?[] AlbumIds { get; set; }
#endif
            /// <summary>Filter by city name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("city")]
            public string? City { get; set; }
#nullable restore
#else
            [QueryParameter("city")]
            public string City { get; set; }
#endif
            /// <summary>Filter by country name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("country")]
            public string? Country { get; set; }
#nullable restore
#else
            [QueryParameter("country")]
            public string Country { get; set; }
#endif
            /// <summary>Filter by creation date (after)</summary>
            [QueryParameter("createdAfter")]
            public DateTimeOffset? CreatedAfter { get; set; }
            /// <summary>Filter by creation date (before)</summary>
            [QueryParameter("createdBefore")]
            public DateTimeOffset? CreatedBefore { get; set; }
            /// <summary>Filter by encoded status</summary>
            [QueryParameter("isEncoded")]
            public bool? IsEncoded { get; set; }
            /// <summary>Filter by favorite status</summary>
            [QueryParameter("isFavorite")]
            public bool? IsFavorite { get; set; }
            /// <summary>Filter by motion photo status</summary>
            [QueryParameter("isMotion")]
            public bool? IsMotion { get; set; }
            /// <summary>Filter assets not in any album</summary>
            [QueryParameter("isNotInAlbum")]
            public bool? IsNotInAlbum { get; set; }
            /// <summary>Filter by offline status</summary>
            [QueryParameter("isOffline")]
            public bool? IsOffline { get; set; }
            /// <summary>Filter by lens model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("lensModel")]
            public string? LensModel { get; set; }
#nullable restore
#else
            [QueryParameter("lensModel")]
            public string LensModel { get; set; }
#endif
            /// <summary>Library ID to filter by</summary>
            [QueryParameter("libraryId")]
            public Guid? LibraryId { get; set; }
            /// <summary>Filter by camera make</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("make")]
            public string? Make { get; set; }
#nullable restore
#else
            [QueryParameter("make")]
            public string Make { get; set; }
#endif
            /// <summary>Minimum file size in bytes</summary>
            [QueryParameter("minFileSize")]
            public int? MinFileSize { get; set; }
            /// <summary>Filter by camera model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("model")]
            public string? Model { get; set; }
#nullable restore
#else
            [QueryParameter("model")]
            public string Model { get; set; }
#endif
            /// <summary>Filter by OCR text content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ocr")]
            public string? Ocr { get; set; }
#nullable restore
#else
            [QueryParameter("ocr")]
            public string Ocr { get; set; }
#endif
            /// <summary>Filter by person IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("personIds")]
            public Guid?[]? PersonIds { get; set; }
#nullable restore
#else
            [QueryParameter("personIds")]
            public Guid?[] PersonIds { get; set; }
#endif
            /// <summary>Filter by rating [1-5], or null for unrated</summary>
            [QueryParameter("rating")]
            public int? Rating { get; set; }
            /// <summary>Number of results to return</summary>
            [QueryParameter("size")]
            public int? Size { get; set; }
            /// <summary>Filter by state/province name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>Filter by tag IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tagIds")]
            public Guid?[]? TagIds { get; set; }
#nullable restore
#else
            [QueryParameter("tagIds")]
            public Guid?[] TagIds { get; set; }
#endif
            /// <summary>Filter by taken date (after)</summary>
            [QueryParameter("takenAfter")]
            public DateTimeOffset? TakenAfter { get; set; }
            /// <summary>Filter by taken date (before)</summary>
            [QueryParameter("takenBefore")]
            public DateTimeOffset? TakenBefore { get; set; }
            /// <summary>Filter by trash date (after)</summary>
            [QueryParameter("trashedAfter")]
            public DateTimeOffset? TrashedAfter { get; set; }
            /// <summary>Filter by trash date (before)</summary>
            [QueryParameter("trashedBefore")]
            public DateTimeOffset? TrashedBefore { get; set; }
            [Obsolete("This property is deprecated, use TypeAsAssetTypeEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
            [QueryParameter("type")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetTypeEnum? TypeAsAssetTypeEnum { get; set; }
            /// <summary>Filter by update date (after)</summary>
            [QueryParameter("updatedAfter")]
            public DateTimeOffset? UpdatedAfter { get; set; }
            /// <summary>Filter by update date (before)</summary>
            [QueryParameter("updatedBefore")]
            public DateTimeOffset? UpdatedBefore { get; set; }
            [Obsolete("This property is deprecated, use VisibilityAsAssetVisibility instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("visibility")]
            public string? Visibility { get; set; }
#nullable restore
#else
            [QueryParameter("visibility")]
            public string Visibility { get; set; }
#endif
            [QueryParameter("visibility")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility? VisibilityAsAssetVisibility { get; set; }
            /// <summary>Include deleted assets</summary>
            [QueryParameter("withDeleted")]
            public bool? WithDeleted { get; set; }
            /// <summary>Include EXIF data in response</summary>
            [QueryParameter("withExif")]
            public bool? WithExif { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LargeAssetsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Search.LargeAssets.LargeAssetsRequestBuilder.LargeAssetsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
