// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.Playback;
namespace VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video
{
    /// <summary>
    /// Builds and executes requests for operations under \assets\{id}\video
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The playback property</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.Playback.PlaybackRequestBuilder Playback
        {
            get => new global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.Playback.PlaybackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.VideoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assets/{id}/video", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.VideoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assets/{id}/video", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
