sonar.projectKey=vormadal_vman
sonar.organization=vormadal

sonar.sources=VideoManager/VManBackend,video-manager-frontend/src
sonar.tests=video-manager-frontend/tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/Generated/**,video-manager-frontend/src/lib/api/client.ts,**/bin/**,**/obj/**,**/Migrations/**
