// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VManBackend.Infrastructure.Immich.Generated.Models;
namespace VManBackend.Infrastructure.Immich.Generated.Download.Info
{
    /// <summary>
    /// Builds and executes requests for operations under \download\info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download/info{?key*,slug*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download/info{?key*,slug*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve information about how to request a download for the specified assets or album. The response includes groups of assets that can be downloaded together.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadResponseDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadResponseDto?> PostAsync(global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadInfoDto body, Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder.InfoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadResponseDto> PostAsync(global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadInfoDto body, Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder.InfoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadResponseDto>(requestInfo, global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve information about how to request a download for the specified assets or album. The response includes groups of assets that can be downloaded together.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadInfoDto body, Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder.InfoRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::VManBackend.Infrastructure.Immich.Generated.Models.DownloadInfoDto body, Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder.InfoRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve information about how to request a download for the specified assets or album. The response includes groups of assets that can be downloaded together.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InfoRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InfoRequestBuilderPostRequestConfiguration : RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Download.Info.InfoRequestBuilder.InfoRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
