// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VManBackend.Infrastructure.Immich.Generated.Models;
namespace VManBackend.Infrastructure.Immich.Generated.Plugins.Methods
{
    /// <summary>
    /// Builds and executes requests for operations under \plugins\methods
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MethodsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MethodsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/plugins/methods{?description*,enabled*,id*,name*,pluginName*,pluginVersion*,title*,trigger*,type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MethodsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/plugins/methods{?description*,enabled*,id*,name*,pluginName*,pluginVersion*,title*,trigger*,type*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a list of plugin methods
        /// </summary>
        /// <returns>A List&lt;global::VManBackend.Infrastructure.Immich.Generated.Models.PluginMethodResponseDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::VManBackend.Infrastructure.Immich.Generated.Models.PluginMethodResponseDto>?> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder.MethodsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::VManBackend.Infrastructure.Immich.Generated.Models.PluginMethodResponseDto>> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder.MethodsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::VManBackend.Infrastructure.Immich.Generated.Models.PluginMethodResponseDto>(requestInfo, global::VManBackend.Infrastructure.Immich.Generated.Models.PluginMethodResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Retrieve a list of plugin methods
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder.MethodsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder.MethodsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a list of plugin methods
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MethodsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("description")]
            public string? Description { get; set; }
#nullable restore
#else
            [QueryParameter("description")]
            public string Description { get; set; }
#endif
            /// <summary>Whether the plugin method is enabled</summary>
            [QueryParameter("enabled")]
            public bool? Enabled { get; set; }
            /// <summary>Plugin method ID</summary>
            [QueryParameter("id")]
            public Guid? Id { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>Plugin name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pluginName")]
            public string? PluginName { get; set; }
#nullable restore
#else
            [QueryParameter("pluginName")]
            public string PluginName { get; set; }
#endif
            /// <summary>Plugin version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pluginVersion")]
            public string? PluginVersion { get; set; }
#nullable restore
#else
            [QueryParameter("pluginVersion")]
            public string PluginVersion { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("title")]
            public string? Title { get; set; }
#nullable restore
#else
            [QueryParameter("title")]
            public string Title { get; set; }
#endif
            /// <summary>Workflow trigger</summary>
            [Obsolete("This property is deprecated, use TriggerAsWorkflowTrigger instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("trigger")]
            public string? Trigger { get; set; }
#nullable restore
#else
            [QueryParameter("trigger")]
            public string Trigger { get; set; }
#endif
            /// <summary>Workflow trigger</summary>
            [QueryParameter("trigger")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.WorkflowTrigger? TriggerAsWorkflowTrigger { get; set; }
            /// <summary>Workflow types</summary>
            [Obsolete("This property is deprecated, use TypeAsWorkflowType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
            /// <summary>Workflow types</summary>
            [QueryParameter("type")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.WorkflowType? TypeAsWorkflowType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MethodsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Plugins.Methods.MethodsRequestBuilder.MethodsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
