// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VManBackend.Infrastructure.Immich.Generated.Models;
namespace VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets
{
    /// <summary>
    /// Builds and executes requests for operations under \timeline\buckets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BucketsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BucketsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/timeline/buckets{?albumId*,bbox*,isFavorite*,isTrashed*,key*,order*,orderBy*,personId*,slug*,tagId*,userId*,visibility*,withCoordinates*,withPartners*,withStacked*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BucketsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/timeline/buckets{?albumId*,bbox*,isFavorite*,isTrashed*,key*,order*,orderBy*,personId*,slug*,tagId*,userId*,visibility*,withCoordinates*,withPartners*,withStacked*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a list of all minimal time buckets.
        /// </summary>
        /// <returns>A List&lt;global::VManBackend.Infrastructure.Immich.Generated.Models.TimeBucketsResponseDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::VManBackend.Infrastructure.Immich.Generated.Models.TimeBucketsResponseDto>?> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder.BucketsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::VManBackend.Infrastructure.Immich.Generated.Models.TimeBucketsResponseDto>> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder.BucketsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::VManBackend.Infrastructure.Immich.Generated.Models.TimeBucketsResponseDto>(requestInfo, global::VManBackend.Infrastructure.Immich.Generated.Models.TimeBucketsResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Retrieve a list of all minimal time buckets.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder.BucketsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder.BucketsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a list of all minimal time buckets.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BucketsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter assets belonging to a specific album</summary>
            [QueryParameter("albumId")]
            public Guid? AlbumId { get; set; }
            /// <summary>Bounding box coordinates as west,south,east,north (WGS84)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bbox")]
            public string? Bbox { get; set; }
#nullable restore
#else
            [QueryParameter("bbox")]
            public string Bbox { get; set; }
#endif
            /// <summary>Filter by favorite status (true for favorites only, false for non-favorites only)</summary>
            [QueryParameter("isFavorite")]
            public bool? IsFavorite { get; set; }
            /// <summary>Filter by trash status (true for trashed assets only, false for non-trashed only)</summary>
            [QueryParameter("isTrashed")]
            public bool? IsTrashed { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
            /// <summary>Sort order for assets within time buckets (ASC for oldest first, DESC for newest first)</summary>
            [Obsolete("This property is deprecated, use OrderAsAssetOrder instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>Sort order for assets within time buckets (ASC for oldest first, DESC for newest first)</summary>
            [QueryParameter("order")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder? OrderAsAssetOrder { get; set; }
            /// <summary>Date to group and order assets by (takenAt for date taken, createdAt for date added to Immich)</summary>
            [Obsolete("This property is deprecated, use OrderByAsAssetOrderBy instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Date to group and order assets by (takenAt for date taken, createdAt for date added to Immich)</summary>
            [QueryParameter("orderBy")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrderBy? OrderByAsAssetOrderBy { get; set; }
            /// <summary>Filter assets containing a specific person (face recognition)</summary>
            [QueryParameter("personId")]
            public Guid? PersonId { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
            /// <summary>Filter assets with a specific tag</summary>
            [QueryParameter("tagId")]
            public Guid? TagId { get; set; }
            /// <summary>Filter assets by specific user ID</summary>
            [QueryParameter("userId")]
            public Guid? UserId { get; set; }
            /// <summary>Filter by asset visibility status (ARCHIVE, TIMELINE, HIDDEN, LOCKED)</summary>
            [Obsolete("This property is deprecated, use VisibilityAsAssetVisibility instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("visibility")]
            public string? Visibility { get; set; }
#nullable restore
#else
            [QueryParameter("visibility")]
            public string Visibility { get; set; }
#endif
            /// <summary>Filter by asset visibility status (ARCHIVE, TIMELINE, HIDDEN, LOCKED)</summary>
            [QueryParameter("visibility")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility? VisibilityAsAssetVisibility { get; set; }
            /// <summary>Include location data in the response</summary>
            [QueryParameter("withCoordinates")]
            public bool? WithCoordinates { get; set; }
            /// <summary>Include assets shared by partners</summary>
            [QueryParameter("withPartners")]
            public bool? WithPartners { get; set; }
            /// <summary>Include stacked assets in the response. When true, only primary assets from stacks are returned.</summary>
            [QueryParameter("withStacked")]
            public bool? WithStacked { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BucketsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Timeline.Buckets.BucketsRequestBuilder.BucketsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
