// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \assets\{id}\video\stream\{sessionId}\{variantIndex}\{filename}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFilenameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFilenameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assets/{id}/video/stream/{sessionId}/{variantIndex}/{filename}{?key*,slug*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFilenameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assets/{id}/video/stream/{sessionId}/{variantIndex}/{filename}{?key*,slug*}", rawUrl)
        {
        }
        /// <summary>
        /// Streams an HLS init segment (init.mp4) or media segment (seg_N.m4s).
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder.WithFilenameItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder.WithFilenameItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Streams an HLS init segment (init.mp4) or media segment (seg_N.m4s).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder.WithFilenameItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder.WithFilenameItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/octet-stream");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Streams an HLS init segment (init.mp4) or media segment (seg_N.m4s).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFilenameItemRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFilenameItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder.WithFilenameItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
