// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item;
using VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.PlaylistM3u8;
namespace VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \assets\{id}\video\stream\{sessionId}\{variantIndex}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVariantIndexItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The playlistM3u8 property</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.PlaylistM3u8.PlaylistM3u8RequestBuilder PlaylistM3u8
        {
            get => new global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.PlaylistM3u8.PlaylistM3u8RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the VManBackend.Infrastructure.Immich.Generated.assets.item.video.stream.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder"/></returns>
        public global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("filename", position);
                return new global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.Item.WithFilenameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.WithVariantIndexItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVariantIndexItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assets/{id}/video/stream/{sessionId}/{variantIndex}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Assets.Item.Video.StreamNamespace.Item.Item.WithVariantIndexItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVariantIndexItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assets/{id}/video/stream/{sessionId}/{variantIndex}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
