// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VManBackend.Infrastructure.Immich.Generated.Sync.Ack;
using VManBackend.Infrastructure.Immich.Generated.Sync.StreamNamespace;
namespace VManBackend.Infrastructure.Immich.Generated.Sync
{
    /// <summary>
    /// Builds and executes requests for operations under \sync
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SyncRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ack property</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Sync.Ack.AckRequestBuilder Ack
        {
            get => new global::VManBackend.Infrastructure.Immich.Generated.Sync.Ack.AckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stream property</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Sync.StreamNamespace.StreamRequestBuilder Stream
        {
            get => new global::VManBackend.Infrastructure.Immich.Generated.Sync.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Sync.SyncRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SyncRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sync", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Sync.SyncRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SyncRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sync", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
