// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VManBackend.Infrastructure.Immich.Generated.Models;
namespace VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap
{
    /// <summary>
    /// Builds and executes requests for operations under \users\me\calendar-heatmap
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CalendarHeatmapRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarHeatmapRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/me/calendar-heatmap{?from*,to*,type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarHeatmapRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/me/calendar-heatmap{?from*,to*,type*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve activity counts for a specified period, in a calendar heatmap format.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.CalendarHeatmapResponseDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::VManBackend.Infrastructure.Immich.Generated.Models.CalendarHeatmapResponseDto?> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder.CalendarHeatmapRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::VManBackend.Infrastructure.Immich.Generated.Models.CalendarHeatmapResponseDto> GetAsync(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder.CalendarHeatmapRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::VManBackend.Infrastructure.Immich.Generated.Models.CalendarHeatmapResponseDto>(requestInfo, global::VManBackend.Infrastructure.Immich.Generated.Models.CalendarHeatmapResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve activity counts for a specified period, in a calendar heatmap format.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder.CalendarHeatmapRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder.CalendarHeatmapRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve activity counts for a specified period, in a calendar heatmap format.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CalendarHeatmapRequestBuilderGetQueryParameters 
        {
            /// <summary>Start date in UTC</summary>
            [QueryParameter("from")]
            public Date? From { get; set; }
            /// <summary>End date in UTC</summary>
            [QueryParameter("to")]
            public Date? To { get; set; }
            [Obsolete("This property is deprecated, use TypeAsCalendarHeatmapType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
            [QueryParameter("type")]
            public global::VManBackend.Infrastructure.Immich.Generated.Models.CalendarHeatmapType? TypeAsCalendarHeatmapType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CalendarHeatmapRequestBuilderGetRequestConfiguration : RequestConfiguration<global::VManBackend.Infrastructure.Immich.Generated.Users.Me.CalendarHeatmap.CalendarHeatmapRequestBuilder.CalendarHeatmapRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
