// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AlbumResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Album name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlbumName { get; set; }
#nullable restore
#else
        public string AlbumName { get; set; }
#endif
        /// <summary>Thumbnail asset ID</summary>
        public Guid? AlbumThumbnailAssetId { get; set; }
        /// <summary>First entry is always the album owner. Second entry is the auth user, if it differs from the owner. The rest are ordered alphabetically.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumUserResponseDto>? AlbumUsers { get; set; }
#nullable restore
#else
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumUserResponseDto> AlbumUsers { get; set; }
#endif
        /// <summary>Number of assets</summary>
        public int? AssetCount { get; set; }
        /// <summary>The contributorCounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.ContributorCountResponseDto>? ContributorCounts { get; set; }
#nullable restore
#else
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.ContributorCountResponseDto> ContributorCounts { get; set; }
#endif
        /// <summary>Creation date</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Album description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>End date (latest asset)</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Has shared link</summary>
        public bool? HasSharedLink { get; set; }
        /// <summary>Album ID</summary>
        public Guid? Id { get; set; }
        /// <summary>Activity feed enabled</summary>
        public bool? IsActivityEnabled { get; set; }
        /// <summary>Last modified asset timestamp</summary>
        public DateTimeOffset? LastModifiedAssetTimestamp { get; set; }
        /// <summary>Asset sort order</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder? Order { get; set; }
        /// <summary>Is shared album</summary>
        public bool? Shared { get; set; }
        /// <summary>Start date (earliest asset)</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Last update date</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto"/> and sets the default values.
        /// </summary>
        public AlbumResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albumName", n => { AlbumName = n.GetStringValue(); } },
                { "albumThumbnailAssetId", n => { AlbumThumbnailAssetId = n.GetGuidValue(); } },
                { "albumUsers", n => { AlbumUsers = n.GetCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumUserResponseDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumUserResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "assetCount", n => { AssetCount = n.GetIntValue(); } },
                { "contributorCounts", n => { ContributorCounts = n.GetCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.ContributorCountResponseDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.ContributorCountResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "hasSharedLink", n => { HasSharedLink = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isActivityEnabled", n => { IsActivityEnabled = n.GetBoolValue(); } },
                { "lastModifiedAssetTimestamp", n => { LastModifiedAssetTimestamp = n.GetDateTimeOffsetValue(); } },
                { "order", n => { Order = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder>(); } },
                { "shared", n => { Shared = n.GetBoolValue(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("albumName", AlbumName);
            writer.WriteGuidValue("albumThumbnailAssetId", AlbumThumbnailAssetId);
            writer.WriteCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumUserResponseDto>("albumUsers", AlbumUsers);
            writer.WriteIntValue("assetCount", AssetCount);
            writer.WriteCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.ContributorCountResponseDto>("contributorCounts", ContributorCounts);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endDate", EndDate);
            writer.WriteBoolValue("hasSharedLink", HasSharedLink);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isActivityEnabled", IsActivityEnabled);
            writer.WriteDateTimeOffsetValue("lastModifiedAssetTimestamp", LastModifiedAssetTimestamp);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder>("order", Order);
            writer.WriteBoolValue("shared", Shared);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
