// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AssetEditActionListDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of edit actions to apply (crop, rotate, or mirror)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits>? Edits { get; set; }
#nullable restore
#else
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits> Edits { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto"/> and sets the default values.
        /// </summary>
        public AssetEditActionListDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "edits", n => { Edits = n.GetCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits>(global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits>("edits", Edits);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionCrop"/>, <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionMirror"/>, <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionRotate"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AssetEditActionListDto_edits : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionCrop"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionCrop? AssetEditActionCrop { get; set; }
#nullable restore
#else
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionCrop AssetEditActionCrop { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionMirror"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionMirror? AssetEditActionMirror { get; set; }
#nullable restore
#else
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionMirror AssetEditActionMirror { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionRotate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionRotate? AssetEditActionRotate { get; set; }
#nullable restore
#else
            public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionRotate AssetEditActionRotate { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionListDto.AssetEditActionListDto_edits();
                result.AssetEditActionCrop = new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionCrop();
                result.AssetEditActionMirror = new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionMirror();
                result.AssetEditActionRotate = new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionRotate();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AssetEditActionCrop != null || AssetEditActionMirror != null || AssetEditActionRotate != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AssetEditActionCrop, AssetEditActionMirror, AssetEditActionRotate);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionCrop>(null, AssetEditActionCrop, AssetEditActionMirror, AssetEditActionRotate);
            }
        }
    }
}
#pragma warning restore CS0618
