// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Asset type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AssetTypeEnum
    {
        [EnumMember(Value = "IMAGE")]
        #pragma warning disable CS1591
        IMAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO")]
        #pragma warning disable CS1591
        VIDEO,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUDIO")]
        #pragma warning disable CS1591
        AUDIO,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
