// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Upload status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AssetMediaStatus
    {
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "replaced")]
        #pragma warning disable CS1591
        Replaced,
        #pragma warning restore CS1591
        [EnumMember(Value = "duplicate")]
        #pragma warning disable CS1591
        Duplicate,
        #pragma warning restore CS1591
    }
}
