// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>
    /// Asset face without person
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssetFaceWithoutPersonResponseDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Bounding box X1 coordinate</summary>
        public int? BoundingBoxX1 { get; set; }
        /// <summary>Bounding box X2 coordinate</summary>
        public int? BoundingBoxX2 { get; set; }
        /// <summary>Bounding box Y1 coordinate</summary>
        public int? BoundingBoxY1 { get; set; }
        /// <summary>Bounding box Y2 coordinate</summary>
        public int? BoundingBoxY2 { get; set; }
        /// <summary>Face ID</summary>
        public Guid? Id { get; set; }
        /// <summary>Image height in pixels</summary>
        public int? ImageHeight { get; set; }
        /// <summary>Image width in pixels</summary>
        public int? ImageWidth { get; set; }
        /// <summary>Face detection source type</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.SourceType? SourceType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetFaceWithoutPersonResponseDto"/> and sets the default values.
        /// </summary>
        public AssetFaceWithoutPersonResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetFaceWithoutPersonResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.AssetFaceWithoutPersonResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetFaceWithoutPersonResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "boundingBoxX1", n => { BoundingBoxX1 = n.GetIntValue(); } },
                { "boundingBoxX2", n => { BoundingBoxX2 = n.GetIntValue(); } },
                { "boundingBoxY1", n => { BoundingBoxY1 = n.GetIntValue(); } },
                { "boundingBoxY2", n => { BoundingBoxY2 = n.GetIntValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "imageHeight", n => { ImageHeight = n.GetIntValue(); } },
                { "imageWidth", n => { ImageWidth = n.GetIntValue(); } },
                { "sourceType", n => { SourceType = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.SourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("boundingBoxX1", BoundingBoxX1);
            writer.WriteIntValue("boundingBoxX2", BoundingBoxX2);
            writer.WriteIntValue("boundingBoxY1", BoundingBoxY1);
            writer.WriteIntValue("boundingBoxY2", BoundingBoxY2);
            writer.WriteGuidValue("id", Id);
            writer.WriteIntValue("imageHeight", ImageHeight);
            writer.WriteIntValue("imageWidth", ImageWidth);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.SourceType>("sourceType", SourceType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
