// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Upload action</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AssetUploadAction
    {
        [EnumMember(Value = "accept")]
        #pragma warning disable CS1591
        Accept,
        #pragma warning restore CS1591
        [EnumMember(Value = "reject")]
        #pragma warning disable CS1591
        Reject,
        #pragma warning restore CS1591
    }
}
