// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Rejection reason if rejected</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AssetRejectReason
    {
        [EnumMember(Value = "duplicate")]
        #pragma warning disable CS1591
        Duplicate,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupported-format")]
        #pragma warning disable CS1591
        UnsupportedFormat,
        #pragma warning restore CS1591
    }
}
