// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Type of edit action to perform</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AssetEditAction
    {
        [EnumMember(Value = "crop")]
        #pragma warning disable CS1591
        Crop,
        #pragma warning restore CS1591
        [EnumMember(Value = "rotate")]
        #pragma warning disable CS1591
        Rotate,
        #pragma warning restore CS1591
        [EnumMember(Value = "mirror")]
        #pragma warning disable CS1591
        Mirror,
        #pragma warning restore CS1591
    }
}
