// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AssetEditActionItemResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Type of edit action to perform</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditAction? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Asset edit ID</summary>
        public Guid? Id { get; set; }
        /// <summary>List of edit actions to apply (crop, rotate, or mirror)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters? Parameters { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters Parameters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto"/> and sets the default values.
        /// </summary>
        public AssetEditActionItemResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditAction>(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters>(global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditAction>("action", Action);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters>("parameters", Parameters);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.CropParameters"/>, <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.MirrorParameters"/>, <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.RotateParameters"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AssetEditActionItemResponseDto_parameters : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.CropParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::VManBackend.Infrastructure.Immich.Generated.Models.CropParameters? CropParameters { get; set; }
#nullable restore
#else
            public global::VManBackend.Infrastructure.Immich.Generated.Models.CropParameters CropParameters { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.MirrorParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::VManBackend.Infrastructure.Immich.Generated.Models.MirrorParameters? MirrorParameters { get; set; }
#nullable restore
#else
            public global::VManBackend.Infrastructure.Immich.Generated.Models.MirrorParameters MirrorParameters { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.RotateParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::VManBackend.Infrastructure.Immich.Generated.Models.RotateParameters? RotateParameters { get; set; }
#nullable restore
#else
            public global::VManBackend.Infrastructure.Immich.Generated.Models.RotateParameters RotateParameters { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::VManBackend.Infrastructure.Immich.Generated.Models.AssetEditActionItemResponseDto.AssetEditActionItemResponseDto_parameters();
                result.CropParameters = new global::VManBackend.Infrastructure.Immich.Generated.Models.CropParameters();
                result.MirrorParameters = new global::VManBackend.Infrastructure.Immich.Generated.Models.MirrorParameters();
                result.RotateParameters = new global::VManBackend.Infrastructure.Immich.Generated.Models.RotateParameters();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CropParameters != null || MirrorParameters != null || RotateParameters != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CropParameters, MirrorParameters, RotateParameters);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.CropParameters>(null, CropParameters, MirrorParameters, RotateParameters);
            }
        }
    }
}
#pragma warning restore CS0618
