// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Colorspace</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Colorspace
    {
        [EnumMember(Value = "srgb")]
        #pragma warning disable CS1591
        Srgb,
        #pragma warning restore CS1591
        [EnumMember(Value = "p3")]
        #pragma warning disable CS1591
        P3,
        #pragma warning restore CS1591
    }
}
