// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Integrity report type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IntegrityReport
    {
        [EnumMember(Value = "untracked_file")]
        #pragma warning disable CS1591
        Untracked_file,
        #pragma warning restore CS1591
        [EnumMember(Value = "missing_file")]
        #pragma warning disable CS1591
        Missing_file,
        #pragma warning restore CS1591
        [EnumMember(Value = "checksum_mismatch")]
        #pragma warning disable CS1591
        Checksum_mismatch,
        #pragma warning restore CS1591
    }
}
