// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Log level</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LogLevel
    {
        [EnumMember(Value = "verbose")]
        #pragma warning disable CS1591
        Verbose,
        #pragma warning restore CS1591
        [EnumMember(Value = "debug")]
        #pragma warning disable CS1591
        Debug,
        #pragma warning restore CS1591
        [EnumMember(Value = "log")]
        #pragma warning disable CS1591
        Log,
        #pragma warning restore CS1591
        [EnumMember(Value = "warn")]
        #pragma warning disable CS1591
        Warn,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "fatal")]
        #pragma warning disable CS1591
        Fatal,
        #pragma warning restore CS1591
    }
}
