// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Memory type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MemoryType
    {
        [EnumMember(Value = "on_this_day")]
        #pragma warning disable CS1591
        On_this_day,
        #pragma warning restore CS1591
    }
}
