// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MemoryResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>? Assets { get; set; }
#nullable restore
#else
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto> Assets { get; set; }
#endif
        /// <summary>Creation date</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.OnThisDayDto? Data { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.OnThisDayDto Data { get; set; }
#endif
        /// <summary>Deletion date</summary>
        public DateTimeOffset? DeletedAt { get; set; }
        /// <summary>Date when memory should be hidden</summary>
        public DateTimeOffset? HideAt { get; set; }
        /// <summary>Memory ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Is memory saved</summary>
        public bool? IsSaved { get; set; }
        /// <summary>Memory date</summary>
        public DateTimeOffset? MemoryAt { get; set; }
        /// <summary>Owner user ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>Date when memory was seen</summary>
        public DateTimeOffset? SeenAt { get; set; }
        /// <summary>Date when memory should be shown</summary>
        public DateTimeOffset? ShowAt { get; set; }
        /// <summary>Memory type</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryType? Type { get; set; }
        /// <summary>Last update date</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryResponseDto"/> and sets the default values.
        /// </summary>
        public MemoryResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assets", n => { Assets = n.GetCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.OnThisDayDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.OnThisDayDto.CreateFromDiscriminatorValue); } },
                { "deletedAt", n => { DeletedAt = n.GetDateTimeOffsetValue(); } },
                { "hideAt", n => { HideAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isSaved", n => { IsSaved = n.GetBoolValue(); } },
                { "memoryAt", n => { MemoryAt = n.GetDateTimeOffsetValue(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "seenAt", n => { SeenAt = n.GetDateTimeOffsetValue(); } },
                { "showAt", n => { ShowAt = n.GetDateTimeOffsetValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryType>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>("assets", Assets);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.OnThisDayDto>("data", Data);
            writer.WriteDateTimeOffsetValue("deletedAt", DeletedAt);
            writer.WriteDateTimeOffsetValue("hideAt", HideAt);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isSaved", IsSaved);
            writer.WriteDateTimeOffsetValue("memoryAt", MemoryAt);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteDateTimeOffsetValue("seenAt", SeenAt);
            writer.WriteDateTimeOffsetValue("showAt", ShowAt);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.MemoryType>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
