// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NotificationCreateDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Additional notification data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto_data? Data { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto_data Data { get; set; }
#endif
        /// <summary>Notification description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Notification level</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationLevel? Level { get; set; }
        /// <summary>Date when notification was read</summary>
        public DateTimeOffset? ReadAt { get; set; }
        /// <summary>Notification title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Notification type</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationType? Type { get; set; }
        /// <summary>User ID to send notification to</summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto"/> and sets the default values.
        /// </summary>
        public NotificationCreateDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto_data>(global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto_data.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "level", n => { Level = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationLevel>(); } },
                { "readAt", n => { ReadAt = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationType>(); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationCreateDto_data>("data", Data);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationLevel>("level", Level);
            writer.WriteDateTimeOffsetValue("readAt", ReadAt);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.NotificationType>("type", Type);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
