// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Token endpoint auth method</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OAuthTokenEndpointAuthMethod
    {
        [EnumMember(Value = "client_secret_post")]
        #pragma warning disable CS1591
        Client_secret_post,
        #pragma warning restore CS1591
        [EnumMember(Value = "client_secret_basic")]
        #pragma warning disable CS1591
        Client_secret_basic,
        #pragma warning restore CS1591
    }
}
