// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Plugin context</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PluginContextType
    {
        [EnumMember(Value = "asset")]
        #pragma warning disable CS1591
        Asset,
        #pragma warning restore CS1591
        [EnumMember(Value = "album")]
        #pragma warning disable CS1591
        Album,
        #pragma warning restore CS1591
        [EnumMember(Value = "person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
    }
}
