// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PluginJsonSchemaType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "integer")]
        #pragma warning disable CS1591
        Integer,
        #pragma warning restore CS1591
        [EnumMember(Value = "boolean")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
        [EnumMember(Value = "object")]
        #pragma warning disable CS1591
        Object,
        #pragma warning restore CS1591
        [EnumMember(Value = "array")]
        #pragma warning disable CS1591
        Array,
        #pragma warning restore CS1591
        [EnumMember(Value = "null")]
        #pragma warning disable CS1591
        Null,
        #pragma warning restore CS1591
    }
}
