// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Trigger type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PluginTriggerType
    {
        [EnumMember(Value = "AssetCreate")]
        #pragma warning disable CS1591
        AssetCreate,
        #pragma warning restore CS1591
        [EnumMember(Value = "PersonRecognized")]
        #pragma warning disable CS1591
        PersonRecognized,
        #pragma warning restore CS1591
    }
}
