// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Queue command to execute</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QueueCommand
    {
        [EnumMember(Value = "start")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause")]
        #pragma warning disable CS1591
        Pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "resume")]
        #pragma warning disable CS1591
        Resume,
        #pragma warning restore CS1591
        [EnumMember(Value = "empty")]
        #pragma warning disable CS1591
        Empty,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear-failed")]
        #pragma warning disable CS1591
        ClearFailed,
        #pragma warning restore CS1591
    }
}
