// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Queue job status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QueueJobStatus
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "delayed")]
        #pragma warning disable CS1591
        Delayed,
        #pragma warning restore CS1591
        [EnumMember(Value = "waiting")]
        #pragma warning disable CS1591
        Waiting,
        #pragma warning restore CS1591
        [EnumMember(Value = "paused")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
    }
}
