// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Reaction type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReactionType
    {
        [EnumMember(Value = "comment")]
        #pragma warning disable CS1591
        Comment,
        #pragma warning restore CS1591
        [EnumMember(Value = "like")]
        #pragma warning disable CS1591
        Like,
        #pragma warning restore CS1591
    }
}
