// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Release channel</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReleaseChannel
    {
        [EnumMember(Value = "stable")]
        #pragma warning disable CS1591
        Stable,
        #pragma warning restore CS1591
        [EnumMember(Value = "releaseCandidate")]
        #pragma warning disable CS1591
        ReleaseCandidate,
        #pragma warning restore CS1591
    }
}
