// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SharedLinkResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The album property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto? Album { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto Album { get; set; }
#endif
        /// <summary>Allow downloads</summary>
        public bool? AllowDownload { get; set; }
        /// <summary>Allow uploads</summary>
        public bool? AllowUpload { get; set; }
        /// <summary>The assets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>? Assets { get; set; }
#nullable restore
#else
        public List<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto> Assets { get; set; }
#endif
        /// <summary>Creation date</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Link description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Expiration date</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>Shared link ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Encryption key (base64url)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>Has password</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>Show metadata</summary>
        public bool? ShowMetadata { get; set; }
        /// <summary>Custom URL slug</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>Access token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>Shared link type</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkType? Type { get; set; }
        /// <summary>Owner user ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkResponseDto"/> and sets the default values.
        /// </summary>
        public SharedLinkResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "album", n => { Album = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto.CreateFromDiscriminatorValue); } },
                { "allowDownload", n => { AllowDownload = n.GetBoolValue(); } },
                { "allowUpload", n => { AllowUpload = n.GetBoolValue(); } },
                { "assets", n => { Assets = n.GetCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "showMetadata", n => { ShowMetadata = n.GetBoolValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkType>(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AlbumResponseDto>("album", Album);
            writer.WriteBoolValue("allowDownload", AllowDownload);
            writer.WriteBoolValue("allowUpload", AllowUpload);
            writer.WriteCollectionOfObjectValues<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetResponseDto>("assets", Assets);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("expiresAt", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("password", Password);
            writer.WriteBoolValue("showMetadata", ShowMetadata);
            writer.WriteStringValue("slug", Slug);
            writer.WriteStringValue("token", Token);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.SharedLinkType>("type", Type);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
