// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Face detection source type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SourceType
    {
        [EnumMember(Value = "machine-learning")]
        #pragma warning disable CS1591
        MachineLearning,
        #pragma warning restore CS1591
        [EnumMember(Value = "exif")]
        #pragma warning disable CS1591
        Exif,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
