// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatisticsSearchDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Filter by album IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? AlbumIds { get; set; }
#nullable restore
#else
        public List<Guid?> AlbumIds { get; set; }
#endif
        /// <summary>Filter by city name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>Filter by country name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>Filter by creation date (after)</summary>
        public DateTimeOffset? CreatedAfter { get; set; }
        /// <summary>Filter by creation date (before)</summary>
        public DateTimeOffset? CreatedBefore { get; set; }
        /// <summary>Filter by description text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Device ID to filter by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceId { get; set; }
#nullable restore
#else
        public string DeviceId { get; set; }
#endif
        /// <summary>Filter by encoded status</summary>
        public bool? IsEncoded { get; set; }
        /// <summary>Filter by favorite status</summary>
        public bool? IsFavorite { get; set; }
        /// <summary>Filter by motion photo status</summary>
        public bool? IsMotion { get; set; }
        /// <summary>Filter assets not in any album</summary>
        public bool? IsNotInAlbum { get; set; }
        /// <summary>Filter by offline status</summary>
        public bool? IsOffline { get; set; }
        /// <summary>Filter by lens model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LensModel { get; set; }
#nullable restore
#else
        public string LensModel { get; set; }
#endif
        /// <summary>Library ID to filter by</summary>
        public Guid? LibraryId { get; set; }
        /// <summary>Filter by camera make</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Make { get; set; }
#nullable restore
#else
        public string Make { get; set; }
#endif
        /// <summary>Filter by camera model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Filter by OCR text content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ocr { get; set; }
#nullable restore
#else
        public string Ocr { get; set; }
#endif
        /// <summary>Filter by person IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? PersonIds { get; set; }
#nullable restore
#else
        public List<Guid?> PersonIds { get; set; }
#endif
        /// <summary>Filter by rating</summary>
        public double? Rating { get; set; }
        /// <summary>Filter by state/province name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Filter by tag IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TagIds { get; set; }
#nullable restore
#else
        public List<Guid?> TagIds { get; set; }
#endif
        /// <summary>Filter by taken date (after)</summary>
        public DateTimeOffset? TakenAfter { get; set; }
        /// <summary>Filter by taken date (before)</summary>
        public DateTimeOffset? TakenBefore { get; set; }
        /// <summary>Filter by trash date (after)</summary>
        public DateTimeOffset? TrashedAfter { get; set; }
        /// <summary>Filter by trash date (before)</summary>
        public DateTimeOffset? TrashedBefore { get; set; }
        /// <summary>Asset type filter</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetTypeEnum? Type { get; set; }
        /// <summary>Filter by update date (after)</summary>
        public DateTimeOffset? UpdatedAfter { get; set; }
        /// <summary>Filter by update date (before)</summary>
        public DateTimeOffset? UpdatedBefore { get; set; }
        /// <summary>Filter by visibility</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.StatisticsSearchDto"/> and sets the default values.
        /// </summary>
        public StatisticsSearchDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.StatisticsSearchDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.StatisticsSearchDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.StatisticsSearchDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albumIds", n => { AlbumIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "createdAfter", n => { CreatedAfter = n.GetDateTimeOffsetValue(); } },
                { "createdBefore", n => { CreatedBefore = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "deviceId", n => { DeviceId = n.GetStringValue(); } },
                { "isEncoded", n => { IsEncoded = n.GetBoolValue(); } },
                { "isFavorite", n => { IsFavorite = n.GetBoolValue(); } },
                { "isMotion", n => { IsMotion = n.GetBoolValue(); } },
                { "isNotInAlbum", n => { IsNotInAlbum = n.GetBoolValue(); } },
                { "isOffline", n => { IsOffline = n.GetBoolValue(); } },
                { "lensModel", n => { LensModel = n.GetStringValue(); } },
                { "libraryId", n => { LibraryId = n.GetGuidValue(); } },
                { "make", n => { Make = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "ocr", n => { Ocr = n.GetStringValue(); } },
                { "personIds", n => { PersonIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "rating", n => { Rating = n.GetDoubleValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "tagIds", n => { TagIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "takenAfter", n => { TakenAfter = n.GetDateTimeOffsetValue(); } },
                { "takenBefore", n => { TakenBefore = n.GetDateTimeOffsetValue(); } },
                { "trashedAfter", n => { TrashedAfter = n.GetDateTimeOffsetValue(); } },
                { "trashedBefore", n => { TrashedBefore = n.GetDateTimeOffsetValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetTypeEnum>(); } },
                { "updatedAfter", n => { UpdatedAfter = n.GetDateTimeOffsetValue(); } },
                { "updatedBefore", n => { UpdatedBefore = n.GetDateTimeOffsetValue(); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<Guid?>("albumIds", AlbumIds);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("country", Country);
            writer.WriteDateTimeOffsetValue("createdAfter", CreatedAfter);
            writer.WriteDateTimeOffsetValue("createdBefore", CreatedBefore);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("deviceId", DeviceId);
            writer.WriteBoolValue("isEncoded", IsEncoded);
            writer.WriteBoolValue("isFavorite", IsFavorite);
            writer.WriteBoolValue("isMotion", IsMotion);
            writer.WriteBoolValue("isNotInAlbum", IsNotInAlbum);
            writer.WriteBoolValue("isOffline", IsOffline);
            writer.WriteStringValue("lensModel", LensModel);
            writer.WriteGuidValue("libraryId", LibraryId);
            writer.WriteStringValue("make", Make);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("ocr", Ocr);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("personIds", PersonIds);
            writer.WriteDoubleValue("rating", Rating);
            writer.WriteStringValue("state", State);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("tagIds", TagIds);
            writer.WriteDateTimeOffsetValue("takenAfter", TakenAfter);
            writer.WriteDateTimeOffsetValue("takenBefore", TakenBefore);
            writer.WriteDateTimeOffsetValue("trashedAfter", TrashedAfter);
            writer.WriteDateTimeOffsetValue("trashedBefore", TrashedBefore);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetTypeEnum>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAfter", UpdatedAfter);
            writer.WriteDateTimeOffsetValue("updatedBefore", UpdatedBefore);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility>("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
