// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Storage folder</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StorageFolder
    {
        [EnumMember(Value = "encoded-video")]
        #pragma warning disable CS1591
        EncodedVideo,
        #pragma warning restore CS1591
        [EnumMember(Value = "library")]
        #pragma warning disable CS1591
        Library,
        #pragma warning restore CS1591
        [EnumMember(Value = "upload")]
        #pragma warning disable CS1591
        Upload,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile")]
        #pragma warning disable CS1591
        Profile,
        #pragma warning restore CS1591
        [EnumMember(Value = "thumbs")]
        #pragma warning disable CS1591
        Thumbs,
        #pragma warning restore CS1591
        [EnumMember(Value = "backups")]
        #pragma warning disable CS1591
        Backups,
        #pragma warning restore CS1591
    }
}
