// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Sync entity type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SyncEntityType
    {
        [EnumMember(Value = "AuthUserV1")]
        #pragma warning disable CS1591
        AuthUserV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "UserV1")]
        #pragma warning disable CS1591
        UserV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "UserDeleteV1")]
        #pragma warning disable CS1591
        UserDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetV1")]
        #pragma warning disable CS1591
        AssetV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetDeleteV1")]
        #pragma warning disable CS1591
        AssetDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetExifV1")]
        #pragma warning disable CS1591
        AssetExifV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetEditV1")]
        #pragma warning disable CS1591
        AssetEditV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetEditDeleteV1")]
        #pragma warning disable CS1591
        AssetEditDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetMetadataV1")]
        #pragma warning disable CS1591
        AssetMetadataV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetMetadataDeleteV1")]
        #pragma warning disable CS1591
        AssetMetadataDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerV1")]
        #pragma warning disable CS1591
        PartnerV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerDeleteV1")]
        #pragma warning disable CS1591
        PartnerDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerAssetV1")]
        #pragma warning disable CS1591
        PartnerAssetV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerAssetBackfillV1")]
        #pragma warning disable CS1591
        PartnerAssetBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerAssetDeleteV1")]
        #pragma warning disable CS1591
        PartnerAssetDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerAssetExifV1")]
        #pragma warning disable CS1591
        PartnerAssetExifV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerAssetExifBackfillV1")]
        #pragma warning disable CS1591
        PartnerAssetExifBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerStackBackfillV1")]
        #pragma warning disable CS1591
        PartnerStackBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerStackDeleteV1")]
        #pragma warning disable CS1591
        PartnerStackDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartnerStackV1")]
        #pragma warning disable CS1591
        PartnerStackV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumV1")]
        #pragma warning disable CS1591
        AlbumV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumV2")]
        #pragma warning disable CS1591
        AlbumV2,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumDeleteV1")]
        #pragma warning disable CS1591
        AlbumDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumUserV1")]
        #pragma warning disable CS1591
        AlbumUserV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumUserBackfillV1")]
        #pragma warning disable CS1591
        AlbumUserBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumUserDeleteV1")]
        #pragma warning disable CS1591
        AlbumUserDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumAssetCreateV1")]
        #pragma warning disable CS1591
        AlbumAssetCreateV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumAssetUpdateV1")]
        #pragma warning disable CS1591
        AlbumAssetUpdateV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumAssetBackfillV1")]
        #pragma warning disable CS1591
        AlbumAssetBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumAssetExifCreateV1")]
        #pragma warning disable CS1591
        AlbumAssetExifCreateV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumAssetExifUpdateV1")]
        #pragma warning disable CS1591
        AlbumAssetExifUpdateV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumAssetExifBackfillV1")]
        #pragma warning disable CS1591
        AlbumAssetExifBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumToAssetV1")]
        #pragma warning disable CS1591
        AlbumToAssetV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumToAssetDeleteV1")]
        #pragma warning disable CS1591
        AlbumToAssetDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlbumToAssetBackfillV1")]
        #pragma warning disable CS1591
        AlbumToAssetBackfillV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "MemoryV1")]
        #pragma warning disable CS1591
        MemoryV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "MemoryDeleteV1")]
        #pragma warning disable CS1591
        MemoryDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "MemoryToAssetV1")]
        #pragma warning disable CS1591
        MemoryToAssetV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "MemoryToAssetDeleteV1")]
        #pragma warning disable CS1591
        MemoryToAssetDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "StackV1")]
        #pragma warning disable CS1591
        StackV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "StackDeleteV1")]
        #pragma warning disable CS1591
        StackDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PersonV1")]
        #pragma warning disable CS1591
        PersonV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PersonDeleteV1")]
        #pragma warning disable CS1591
        PersonDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetFaceV1")]
        #pragma warning disable CS1591
        AssetFaceV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetFaceV2")]
        #pragma warning disable CS1591
        AssetFaceV2,
        #pragma warning restore CS1591
        [EnumMember(Value = "AssetFaceDeleteV1")]
        #pragma warning disable CS1591
        AssetFaceDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "UserMetadataV1")]
        #pragma warning disable CS1591
        UserMetadataV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "UserMetadataDeleteV1")]
        #pragma warning disable CS1591
        UserMetadataDeleteV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SyncAckV1")]
        #pragma warning disable CS1591
        SyncAckV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SyncResetV1")]
        #pragma warning disable CS1591
        SyncResetV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SyncCompleteV1")]
        #pragma warning disable CS1591
        SyncCompleteV1,
        #pragma warning restore CS1591
    }
}
