// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemConfigOAuthDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allow insecure requests</summary>
        public bool? AllowInsecureRequests { get; set; }
        /// <summary>Auto launch</summary>
        public bool? AutoLaunch { get; set; }
        /// <summary>Auto register</summary>
        public bool? AutoRegister { get; set; }
        /// <summary>Button text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ButtonText { get; set; }
#nullable restore
#else
        public string ButtonText { get; set; }
#endif
        /// <summary>Client ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>Client secret</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientSecret { get; set; }
#nullable restore
#else
        public string ClientSecret { get; set; }
#endif
        /// <summary>Default storage quota</summary>
        public double? DefaultStorageQuota { get; set; }
        /// <summary>Enabled</summary>
        public bool? Enabled { get; set; }
        /// <summary>End session endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndSessionEndpoint { get; set; }
#nullable restore
#else
        public string EndSessionEndpoint { get; set; }
#endif
        /// <summary>Issuer URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuerUrl { get; set; }
#nullable restore
#else
        public string IssuerUrl { get; set; }
#endif
        /// <summary>Mobile override enabled</summary>
        public bool? MobileOverrideEnabled { get; set; }
        /// <summary>Mobile redirect URI (set to empty string to disable)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MobileRedirectUri { get; set; }
#nullable restore
#else
        public string MobileRedirectUri { get; set; }
#endif
        /// <summary>Profile signing algorithm</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileSigningAlgorithm { get; set; }
#nullable restore
#else
        public string ProfileSigningAlgorithm { get; set; }
#endif
        /// <summary>OAuth prompt parameter (e.g. select_account, login, consent)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Role claim</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoleClaim { get; set; }
#nullable restore
#else
        public string RoleClaim { get; set; }
#endif
        /// <summary>Scope</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scope { get; set; }
#nullable restore
#else
        public string Scope { get; set; }
#endif
        /// <summary>Signing algorithm</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningAlgorithm { get; set; }
#nullable restore
#else
        public string SigningAlgorithm { get; set; }
#endif
        /// <summary>Storage label claim</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageLabelClaim { get; set; }
#nullable restore
#else
        public string StorageLabelClaim { get; set; }
#endif
        /// <summary>Storage quota claim</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageQuotaClaim { get; set; }
#nullable restore
#else
        public string StorageQuotaClaim { get; set; }
#endif
        /// <summary>Timeout</summary>
        public int? Timeout { get; set; }
        /// <summary>OAuth token endpoint auth method</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.OAuthTokenEndpointAuthMethod? TokenEndpointAuthMethod { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigOAuthDto"/> and sets the default values.
        /// </summary>
        public SystemConfigOAuthDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigOAuthDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigOAuthDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigOAuthDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowInsecureRequests", n => { AllowInsecureRequests = n.GetBoolValue(); } },
                { "autoLaunch", n => { AutoLaunch = n.GetBoolValue(); } },
                { "autoRegister", n => { AutoRegister = n.GetBoolValue(); } },
                { "buttonText", n => { ButtonText = n.GetStringValue(); } },
                { "clientId", n => { ClientId = n.GetStringValue(); } },
                { "clientSecret", n => { ClientSecret = n.GetStringValue(); } },
                { "defaultStorageQuota", n => { DefaultStorageQuota = n.GetDoubleValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "endSessionEndpoint", n => { EndSessionEndpoint = n.GetStringValue(); } },
                { "issuerUrl", n => { IssuerUrl = n.GetStringValue(); } },
                { "mobileOverrideEnabled", n => { MobileOverrideEnabled = n.GetBoolValue(); } },
                { "mobileRedirectUri", n => { MobileRedirectUri = n.GetStringValue(); } },
                { "profileSigningAlgorithm", n => { ProfileSigningAlgorithm = n.GetStringValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "roleClaim", n => { RoleClaim = n.GetStringValue(); } },
                { "scope", n => { Scope = n.GetStringValue(); } },
                { "signingAlgorithm", n => { SigningAlgorithm = n.GetStringValue(); } },
                { "storageLabelClaim", n => { StorageLabelClaim = n.GetStringValue(); } },
                { "storageQuotaClaim", n => { StorageQuotaClaim = n.GetStringValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "tokenEndpointAuthMethod", n => { TokenEndpointAuthMethod = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.OAuthTokenEndpointAuthMethod>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowInsecureRequests", AllowInsecureRequests);
            writer.WriteBoolValue("autoLaunch", AutoLaunch);
            writer.WriteBoolValue("autoRegister", AutoRegister);
            writer.WriteStringValue("buttonText", ButtonText);
            writer.WriteStringValue("clientId", ClientId);
            writer.WriteStringValue("clientSecret", ClientSecret);
            writer.WriteDoubleValue("defaultStorageQuota", DefaultStorageQuota);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("endSessionEndpoint", EndSessionEndpoint);
            writer.WriteStringValue("issuerUrl", IssuerUrl);
            writer.WriteBoolValue("mobileOverrideEnabled", MobileOverrideEnabled);
            writer.WriteStringValue("mobileRedirectUri", MobileRedirectUri);
            writer.WriteStringValue("profileSigningAlgorithm", ProfileSigningAlgorithm);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("roleClaim", RoleClaim);
            writer.WriteStringValue("scope", Scope);
            writer.WriteStringValue("signingAlgorithm", SigningAlgorithm);
            writer.WriteStringValue("storageLabelClaim", StorageLabelClaim);
            writer.WriteStringValue("storageQuotaClaim", StorageQuotaClaim);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.OAuthTokenEndpointAuthMethod>("tokenEndpointAuthMethod", TokenEndpointAuthMethod);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
