// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemConfigMachineLearningDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The availabilityChecks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.MachineLearningAvailabilityChecksDto? AvailabilityChecks { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.MachineLearningAvailabilityChecksDto AvailabilityChecks { get; set; }
#endif
        /// <summary>The clip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.CLIPConfig? Clip { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.CLIPConfig Clip { get; set; }
#endif
        /// <summary>The duplicateDetection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.DuplicateDetectionConfig? DuplicateDetection { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.DuplicateDetectionConfig DuplicateDetection { get; set; }
#endif
        /// <summary>Enabled</summary>
        public bool? Enabled { get; set; }
        /// <summary>The facialRecognition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.FacialRecognitionConfig? FacialRecognition { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.FacialRecognitionConfig FacialRecognition { get; set; }
#endif
        /// <summary>The ocr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.OcrConfig? Ocr { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.OcrConfig Ocr { get; set; }
#endif
        /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Urls { get; set; }
#nullable restore
#else
        public List<string> Urls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigMachineLearningDto"/> and sets the default values.
        /// </summary>
        public SystemConfigMachineLearningDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigMachineLearningDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigMachineLearningDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigMachineLearningDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availabilityChecks", n => { AvailabilityChecks = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.MachineLearningAvailabilityChecksDto>(global::VManBackend.Infrastructure.Immich.Generated.Models.MachineLearningAvailabilityChecksDto.CreateFromDiscriminatorValue); } },
                { "clip", n => { Clip = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.CLIPConfig>(global::VManBackend.Infrastructure.Immich.Generated.Models.CLIPConfig.CreateFromDiscriminatorValue); } },
                { "duplicateDetection", n => { DuplicateDetection = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.DuplicateDetectionConfig>(global::VManBackend.Infrastructure.Immich.Generated.Models.DuplicateDetectionConfig.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "facialRecognition", n => { FacialRecognition = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.FacialRecognitionConfig>(global::VManBackend.Infrastructure.Immich.Generated.Models.FacialRecognitionConfig.CreateFromDiscriminatorValue); } },
                { "ocr", n => { Ocr = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.OcrConfig>(global::VManBackend.Infrastructure.Immich.Generated.Models.OcrConfig.CreateFromDiscriminatorValue); } },
                { "urls", n => { Urls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.MachineLearningAvailabilityChecksDto>("availabilityChecks", AvailabilityChecks);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.CLIPConfig>("clip", Clip);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.DuplicateDetectionConfig>("duplicateDetection", DuplicateDetection);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.FacialRecognitionConfig>("facialRecognition", FacialRecognition);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.OcrConfig>("ocr", Ocr);
            writer.WriteCollectionOfPrimitiveValues<string>("urls", Urls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
