// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemConfigGeneratedFullsizeImageDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enabled</summary>
        public bool? Enabled { get; set; }
        /// <summary>Image format</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.ImageFormat? Format { get; set; }
        /// <summary>Progressive</summary>
        public bool? Progressive { get; set; }
        /// <summary>Quality</summary>
        public int? Quality { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigGeneratedFullsizeImageDto"/> and sets the default values.
        /// </summary>
        public SystemConfigGeneratedFullsizeImageDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigGeneratedFullsizeImageDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigGeneratedFullsizeImageDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.SystemConfigGeneratedFullsizeImageDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.ImageFormat>(); } },
                { "progressive", n => { Progressive = n.GetBoolValue(); } },
                { "quality", n => { Quality = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.ImageFormat>("format", Format);
            writer.WriteBoolValue("progressive", Progressive);
            writer.WriteIntValue("quality", Quality);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
