// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Tone mapping</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ToneMapping
    {
        [EnumMember(Value = "hable")]
        #pragma warning disable CS1591
        Hable,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobius")]
        #pragma warning disable CS1591
        Mobius,
        #pragma warning restore CS1591
        [EnumMember(Value = "reinhard")]
        #pragma warning disable CS1591
        Reinhard,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
    }
}
