// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Transcode hardware acceleration</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TranscodeHWAccel
    {
        [EnumMember(Value = "nvenc")]
        #pragma warning disable CS1591
        Nvenc,
        #pragma warning restore CS1591
        [EnumMember(Value = "qsv")]
        #pragma warning disable CS1591
        Qsv,
        #pragma warning restore CS1591
        [EnumMember(Value = "vaapi")]
        #pragma warning disable CS1591
        Vaapi,
        #pragma warning restore CS1591
        [EnumMember(Value = "rkmpp")]
        #pragma warning disable CS1591
        Rkmpp,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
    }
}
