// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateAssetDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Original date and time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTimeOriginal { get; set; }
#nullable restore
#else
        public string DateTimeOriginal { get; set; }
#endif
        /// <summary>Asset description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Mark as favorite</summary>
        public bool? IsFavorite { get; set; }
        /// <summary>Latitude coordinate</summary>
        public double? Latitude { get; set; }
        /// <summary>Live photo video ID</summary>
        public Guid? LivePhotoVideoId { get; set; }
        /// <summary>Longitude coordinate</summary>
        public double? Longitude { get; set; }
        /// <summary>Rating in range [1-5] (starred), -1 (rejected), or null (unrated)</summary>
        public int? Rating { get; set; }
        /// <summary>Asset visibility</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAssetDto"/> and sets the default values.
        /// </summary>
        public UpdateAssetDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAssetDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAssetDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAssetDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dateTimeOriginal", n => { DateTimeOriginal = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "isFavorite", n => { IsFavorite = n.GetBoolValue(); } },
                { "latitude", n => { Latitude = n.GetDoubleValue(); } },
                { "livePhotoVideoId", n => { LivePhotoVideoId = n.GetGuidValue(); } },
                { "longitude", n => { Longitude = n.GetDoubleValue(); } },
                { "rating", n => { Rating = n.GetIntValue(); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dateTimeOriginal", DateTimeOriginal);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("isFavorite", IsFavorite);
            writer.WriteDoubleValue("latitude", Latitude);
            writer.WriteGuidValue("livePhotoVideoId", LivePhotoVideoId);
            writer.WriteDoubleValue("longitude", Longitude);
            writer.WriteIntValue("rating", Rating);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetVisibility>("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
