// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateAlbumDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Album name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlbumName { get; set; }
#nullable restore
#else
        public string AlbumName { get; set; }
#endif
        /// <summary>Album thumbnail asset ID</summary>
        public Guid? AlbumThumbnailAssetId { get; set; }
        /// <summary>Album description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Enable activity feed</summary>
        public bool? IsActivityEnabled { get; set; }
        /// <summary>Asset sort order</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder? Order { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAlbumDto"/> and sets the default values.
        /// </summary>
        public UpdateAlbumDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAlbumDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAlbumDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.UpdateAlbumDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albumName", n => { AlbumName = n.GetStringValue(); } },
                { "albumThumbnailAssetId", n => { AlbumThumbnailAssetId = n.GetGuidValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "isActivityEnabled", n => { IsActivityEnabled = n.GetBoolValue(); } },
                { "order", n => { Order = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("albumName", AlbumName);
            writer.WriteGuidValue("albumThumbnailAssetId", AlbumThumbnailAssetId);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("isActivityEnabled", IsActivityEnabled);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.AssetOrder>("order", Order);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
