// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserAdminResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>User avatar color</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.UserAvatarColor? AvatarColor { get; set; }
        /// <summary>Creation date</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Deletion date</summary>
        public DateTimeOffset? DeletedAt { get; set; }
        /// <summary>User email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>User ID</summary>
        public Guid? Id { get; set; }
        /// <summary>Is admin user</summary>
        public bool? IsAdmin { get; set; }
        /// <summary>The license property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VManBackend.Infrastructure.Immich.Generated.Models.UserLicense? License { get; set; }
#nullable restore
#else
        public global::VManBackend.Infrastructure.Immich.Generated.Models.UserLicense License { get; set; }
#endif
        /// <summary>User name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>OAuth ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OauthId { get; set; }
#nullable restore
#else
        public string OauthId { get; set; }
#endif
        /// <summary>Profile change date</summary>
        public DateTimeOffset? ProfileChangedAt { get; set; }
        /// <summary>Profile image path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileImagePath { get; set; }
#nullable restore
#else
        public string ProfileImagePath { get; set; }
#endif
        /// <summary>Storage quota in bytes</summary>
        public int? QuotaSizeInBytes { get; set; }
        /// <summary>Storage usage in bytes</summary>
        public int? QuotaUsageInBytes { get; set; }
        /// <summary>Require password change on next login</summary>
        public bool? ShouldChangePassword { get; set; }
        /// <summary>User status</summary>
        public global::VManBackend.Infrastructure.Immich.Generated.Models.UserStatus? Status { get; set; }
        /// <summary>Storage label</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageLabel { get; set; }
#nullable restore
#else
        public string StorageLabel { get; set; }
#endif
        /// <summary>Last update date</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.UserAdminResponseDto"/> and sets the default values.
        /// </summary>
        public UserAdminResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VManBackend.Infrastructure.Immich.Generated.Models.UserAdminResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VManBackend.Infrastructure.Immich.Generated.Models.UserAdminResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VManBackend.Infrastructure.Immich.Generated.Models.UserAdminResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatarColor", n => { AvatarColor = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.UserAvatarColor>(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deletedAt", n => { DeletedAt = n.GetDateTimeOffsetValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isAdmin", n => { IsAdmin = n.GetBoolValue(); } },
                { "license", n => { License = n.GetObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.UserLicense>(global::VManBackend.Infrastructure.Immich.Generated.Models.UserLicense.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "oauthId", n => { OauthId = n.GetStringValue(); } },
                { "profileChangedAt", n => { ProfileChangedAt = n.GetDateTimeOffsetValue(); } },
                { "profileImagePath", n => { ProfileImagePath = n.GetStringValue(); } },
                { "quotaSizeInBytes", n => { QuotaSizeInBytes = n.GetIntValue(); } },
                { "quotaUsageInBytes", n => { QuotaUsageInBytes = n.GetIntValue(); } },
                { "shouldChangePassword", n => { ShouldChangePassword = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.UserStatus>(); } },
                { "storageLabel", n => { StorageLabel = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.UserAvatarColor>("avatarColor", AvatarColor);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteDateTimeOffsetValue("deletedAt", DeletedAt);
            writer.WriteStringValue("email", Email);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isAdmin", IsAdmin);
            writer.WriteObjectValue<global::VManBackend.Infrastructure.Immich.Generated.Models.UserLicense>("license", License);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("oauthId", OauthId);
            writer.WriteDateTimeOffsetValue("profileChangedAt", ProfileChangedAt);
            writer.WriteStringValue("profileImagePath", ProfileImagePath);
            writer.WriteIntValue("quotaSizeInBytes", QuotaSizeInBytes);
            writer.WriteIntValue("quotaUsageInBytes", QuotaUsageInBytes);
            writer.WriteBoolValue("shouldChangePassword", ShouldChangePassword);
            writer.WriteEnumValue<global::VManBackend.Infrastructure.Immich.Generated.Models.UserStatus>("status", Status);
            writer.WriteStringValue("storageLabel", StorageLabel);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
