// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Avatar color</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserAvatarColor
    {
        [EnumMember(Value = "primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "pink")]
        #pragma warning disable CS1591
        Pink,
        #pragma warning restore CS1591
        [EnumMember(Value = "red")]
        #pragma warning disable CS1591
        Red,
        #pragma warning restore CS1591
        [EnumMember(Value = "yellow")]
        #pragma warning disable CS1591
        Yellow,
        #pragma warning restore CS1591
        [EnumMember(Value = "blue")]
        #pragma warning disable CS1591
        Blue,
        #pragma warning restore CS1591
        [EnumMember(Value = "green")]
        #pragma warning disable CS1591
        Green,
        #pragma warning restore CS1591
        [EnumMember(Value = "purple")]
        #pragma warning disable CS1591
        Purple,
        #pragma warning restore CS1591
        [EnumMember(Value = "orange")]
        #pragma warning disable CS1591
        Orange,
        #pragma warning restore CS1591
        [EnumMember(Value = "gray")]
        #pragma warning disable CS1591
        Gray,
        #pragma warning restore CS1591
        [EnumMember(Value = "amber")]
        #pragma warning disable CS1591
        Amber,
        #pragma warning restore CS1591
    }
}
