// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VManBackend.Infrastructure.Immich.Generated.Models
{
    /// <summary>Target video codec</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoCodec
    {
        [EnumMember(Value = "h264")]
        #pragma warning disable CS1591
        H264,
        #pragma warning restore CS1591
        [EnumMember(Value = "hevc")]
        #pragma warning disable CS1591
        Hevc,
        #pragma warning restore CS1591
        [EnumMember(Value = "vp9")]
        #pragma warning disable CS1591
        Vp9,
        #pragma warning restore CS1591
        [EnumMember(Value = "av1")]
        #pragma warning disable CS1591
        Av1,
        #pragma warning restore CS1591
    }
}
